# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-08-21 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('notify', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='upload_material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('upload', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=25)),
            ],
        ),
    ]
