# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-08-21 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_notificationmodel_upload_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=100)),
                ('clas', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('rno', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
    ]
