# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-08-21 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teachermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='day',
            field=models.IntegerField(),
        ),
    ]
