# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-08-22 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad_staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staffname', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
    ]
